packages:
  - 'client'
  - 'server'
  - 'shared'
  - 'tools/*'
pmOnFail: error
minimumReleaseAgeStrict: true
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  esbuild: true
  msgpackr-extract: false
